# Generated by Django 5.2.4 on 2026-08-24 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('venue', models.CharField(max_length=180)),
                ('city', models.CharField(default='Lagos', max_length=80)),
                ('event_date', models.DateTimeField()),
                ('ticket_type', models.CharField(default='General admission', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('delivery_note', models.CharField(default='Ticket details released by the seller', max_length=180)),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_email', models.EmailField(max_length=254)),
                ('seller_bank', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_bank', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('in_escrow', 'In escrow'), ('delivered', 'Ticket delivered'), ('released', 'Funds released'), ('refund_requested', 'Refund requested'), ('refunded', 'Refunded')], default='awaiting_payment', max_length=30)),
                ('ticket_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.listing')),
            ],
        ),
    ]
