# Generated by Django 5.2.4 on 2026-08-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_exchangelink_listing_seller_order_buyer_emailotp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='seller_account_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller_bank_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_account_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_account_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_bank_code',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
