# Generated by Django 5.2.4 on 2026-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_order_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bachs_destination_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bachs_destination_status',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
