# Generated by Django 5.2.4 on 2026-08-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_bankaccount_bachs_destination_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
