# Generated by Django 5.2.4 on 2026-08-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_order_payment_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('awaiting_payment', 'Awaiting payment'), ('expired', 'Reservation expired'), ('in_escrow', 'In escrow'), ('delivered', 'Ticket delivered'), ('released', 'Funds released'), ('refund_requested', 'Refund requested'), ('refunded', 'Refunded')], default='awaiting_payment', max_length=30),
        ),
    ]
