# Generated by Django 5.2.4 on 2026-08-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_exchangelink_ticket_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangelink',
            name='ticket_file_name',
        ),
        migrations.RemoveField(
            model_name='exchangelink',
            name='ticket_file_type',
        ),
        migrations.RemoveField(
            model_name='exchangelink',
            name='ticket_file_url',
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_file_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='ticket_file_url',
            field=models.URLField(blank=True),
        ),
    ]
