# Generated by Django 5.2.4 on 2026-08-24 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
