# Generated by Django 5.2.4 on 2026-08-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_order_buyer_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_initiated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='order',
            name='payout_status',
            field=models.CharField(default='not_started', max_length=20),
        ),
    ]
