# Generated by Django 5.2.4 on 2026-08-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_order_payout_amount_order_payout_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
