# Generated by Django 5.2.4 on 2026-08-25 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_order_payment_provider_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='BachsWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=160)),
                ('event_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='received', max_length=40)),
                ('signature_valid', models.BooleanField(default=False)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bachs_webhook_deliveries', to='marketplace.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
